#!/usr/bin/python

# Euler #2
#Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
#
#1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
#
#By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

last_term = 1
term = 0
tot = 0

while term < 4000000:
	if (term % 2):
		tot += term
	tmp = term
	term = term + last_term
	last_term = tmp

print tot